### ISSUE TITLE
Issue during the operating process

### ISSUE THREAD

**Issue by wonr469** [ahernanzl/pyClim-SDM#47] opened 2024-09-05 02:00 UTC
I have a new error during operation. So create this issue.

`pr historical ACCESS-CM2_r1i1p1f1 RAW Processing
pr RAW historical ACCESS-CM2_r1i1p1f1 
ERROR retrieving dates from netCDF models files 
Make sure your input_data/models directory contains the needed files. 
At least one direct predictors is needed, not only derived predictors.`

**Comment by ahernanzl** [comment] 2024-09-05 07:03
Hi, 
select only one predictor (pr in this case) and copy this line of code before the 'try' at line 281 of the lib/read.py file:
                dates = np.ndarray.tolist(read.one_direct_predictor(pred, level=level, grid='ext', model=model, scene=scene)['times'])

That will tell us why the model file is not beeing read properly

**Comment by wonr469** [comment] 2024-09-06 02:03
Hello sir, after copy that line of code before the 'try' at line 281 of the lib/read.py file, the error shows like this:
[ErrorResult01.txt](https://github.com/user-attachments/files/16901898/ErrorResult01.txt)

**Comment by ahernanzl** [comment] 2024-09-06 06:25
Hello, 
the problem is your reanalysis files contain the variable time under the name 'valid_time' but your model files do it under the name 'time'. It should be easy to overcome by adapting the lib/read.py file. Move line 64 ( time_name = 'time') to line 80, and then change lines 80-83:

    time_name = 'time'
    calendar = nc.variables[time_name].calendar
    units = nc.variables[time_name].units
    times_num = nc.variables[time_name][:].data

For this piece of code:

    try:
        time_name = 'valid_time'
        calendar = nc.variables[time_name].calendar
        units = nc.variables[time_name].units
        times_num = nc.variables[time_name][:].data
    except:
        time_name = 'time'
        calendar = nc.variables[time_name].calendar
        units = nc.variables[time_name].units
        times_num = nc.variables[time_name][:].data

**Comment by wonr469** [comment] 2024-09-07 13:16
This error has successfully solved, but here is a new error.
[ErrorResult02.txt](https://github.com/user-attachments/files/16918363/ErrorResult02.txt)

**Comment by wonr469** [comment] 2024-09-09 07:44
I have updated down_scene_RAW.py, and restarted operating. If any new orror happens, I will put it in the next comment.

**Comment by ahernanzl** [comment] 2024-09-09 08:24
Hello, do I understand the error was solved? If so, please close this issue

**Comment by wonr469** [comment] 2024-09-09 08:25
The newest error looks like this:
`Traceback (most recent call last):
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 18, in &lt;module&gt;
    main()
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 11, in main
    process.downscale()
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/process.py", line 185, in downscale
    models(method_dict, scene, model)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/process.py", line 106, in models
    down_scene_RAW.downscale_chunk(targetVar, methodName, family, mode, fields, scene, model)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/down_scene_RAW.py", line 123, in downscale_chunk
    X_test = grids.interpolate_predictors(var_scene, i_4nn[ipoint], j_4nn[ipoint], w_4nn[ipoint], interp, targetVar, forceNormalInterpolation=True)
TypeError: interpolate_predictors() got an unexpected keyword argument 'forceNormalInterpolation'`

**Comment by ahernanzl** [comment] 2024-09-09 08:40
Is it possible that you have updated the down_scene_RAW.py file but you haven´t updated the other files? If you only update part of the software there are inconsistencies between files...

**Comment by wonr469** [comment] 2024-09-09 13:29
So I just changed every document in the lib file and restart again, a new error called "NameError: name 'force_fillNans_for_local_predictors' is not defined", from File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/transform.py", line 77, in get_transformation_parameters_reanalysis, 
if force_fillNans_for_local_predictors == True and (np.sum(np.where(np.isnan(ref_data))) != 0):

**Comment by ahernanzl** [comment] 2024-09-09 13:50
Hello, the software is not expected to work properly if you mix files from one version with files from other versions. If you update the software, you need to update all files

**Closed as completed by ahernanzl** 2024-09-09 13:50 UTC

**Comment by wonr469** [comment] 2024-09-09 14:18
Okay. I give in update them. I have restored it to the previous version for the lib file.
